name: flow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
permissions:
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: setup git
        run: |
          git config user.name "iptv-bot[bot]"
          git config user.email "84861620+iptv-bot[bot]@users.noreply.github.com"
      - name: install dependencies
        run: npm install
      - name: grab epg
        run: npm run grab -- --channels flow.channels.xml --days 2 --output guide.xml
      - name: commit and push guide.xml
        run: |
          FILE=guide.xml
          if [ -f "$FILE" ]; then
            git add "$FILE"
            git commit -m "Update guide.xml $(date +'%Y%m%d')" --no-verify
            git push
          fi